'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MMaterialDBiaya
    Public Property NoID As System.Guid
    Public Property IDMaterial As System.Guid
    Public Property IDAkun As Long
    Public Property Jumlah As Decimal
    Public Property Keterangan As String

    Public Overridable Property MAssemblyDBiayas As ICollection(Of MAssemblyDBiaya) = New HashSet(Of MAssemblyDBiaya)
    Public Overridable Property MMaterial As MMaterial

End Class
