'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBPOS1Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBPOS1Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property MAssemblies() As DbSet(Of MAssembly)
    Public Overridable Property MAssemblyDs() As DbSet(Of MAssemblyD)
    Public Overridable Property MAssemblyDBiayas() As DbSet(Of MAssemblyDBiaya)
    Public Overridable Property MAssemblyDSisas() As DbSet(Of MAssemblyDSisa)
    Public Overridable Property MMaterials() As DbSet(Of MMaterial)
    Public Overridable Property MMaterialDs() As DbSet(Of MMaterialD)
    Public Overridable Property MMaterialDBiayas() As DbSet(Of MMaterialDBiaya)
    Public Overridable Property MMaterialDSisas() As DbSet(Of MMaterialDSisa)
    Public Overridable Property MWOAssemblies() As DbSet(Of MWOAssembly)

End Class
