'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model
    Public Class MMaterialDBiaya
        Public Sub New()
            Me.NoID = System.Guid.NewGuid
            Me.IDMaterial = System.Guid.NewGuid
        End Sub

        Public Property NoID As System.Guid
        Public Property IDMaterial As System.Guid
        Public Property IDAkun As Long
        Public Property Jumlah As Decimal
        Public Property Keterangan As String
    End Class
End Namespace