'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model
    Public Class MMaterialD
        Public Sub New()
            Me.NoID = System.Guid.NewGuid
            Me.IDMaterial = System.Guid.NewGuid
        End Sub

        Public Property NoID As System.Guid
        Public Property IDMaterial As System.Guid
        Public Property IDBarangD As Long
        Public Property IDBarang As Long
        Public Property IDSatuan As Integer
        Public Property Konversi As Decimal
        Public Property Qty As Decimal
        Public Property HargaPokok As Decimal
        Public Property Jumlah As Decimal
            Get
                Return System.Math.Round(Qty * HargaPokok, 2)
            End Get
            Set(value As Decimal)

            End Set
        End Property
        Public Property Barcode As String
        Public Property KodeBarang As String
        Public Property NamaBarang As String
        Public Property Satuan As String
    End Class
End Namespace